### ISSUE TITLE
[ISSUE] The provided endpoint + token is not correct.

### ISSUE THREAD

**Issue by Teonyr** [cioraneanu/firefly-pico#1]
### Issue
Hey, I'm trying to get pico up and running.
Since I already have a firefly instance on docker, I used the `docker-compose.pico.yml` as a start.

But when entering my access token, I receive "The provided endpoint + token is not correct."
![grafik](https://github.com/cioraneanu/firefly-pico/assets/75175693/2a95c732-2153-4750-a62a-d3e7f9d05fce)

No matter what I enter there, it always shows the same error.

### docker-compose.yml
(Only the pico - part)
```
  firefly-pico:
    image: cioraneanu/firefly-pico:latest
    container_name: firefly-pico
    environment:
      - FIREFLY_URL=http://firefly-app
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly-pico-postgresql
      - DB_PORT=5432
      - DB_DATABASE=firefly-pico
      - DB_USERNAME=firefly-pico
      - DB_PASSWORD=[REDACTED]
    depends_on:
      - firefly-pico-postgresql
    labels:
      traefik.enable: true
      traefik.http.routers.firefly-pico.entrypoints: web, websecure
      traefik.http.routers.firefly-pico.tls: true
      traefik.http.routers.firefly-pico.rule: (Host(`financepico.anubis.arpa`) )
      traefik.http.services.firefly-pico.loadbalancer.server.port: 80
      traefik.http.services.firefly-pico.loadbalancer.passHostHeader: true
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 6976:80
  firefly-pico-postgresql:
    container_name: firefly-pico-postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: firefly-pico
      POSTGRES_USER: firefly-pico
      POSTGRES_PASSWORD: [REDACTED]
    volumes:
      - /persistent/firefly/pico:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    external: true
```

### Log

> 06.05.2024 10:40:14 /docker-entrypoint.d/ is not empty, will attempt to perform configuration
> 06.05.2024 10:40:14 Looking for shell scripts in /docker-entrypoint.d/
> 06.05.2024 10:40:14 Launching /docker-entrypoint.d/1-configure-php.sh
> 06.05.2024 10:40:14 Configure php
> 06.05.2024 10:40:14 Launching /docker-entrypoint.d/2-configure-php-opcache.sh
> 06.05.2024 10:40:14 Configure php opcache
> 06.05.2024 10:40:14 Launching /docker-entrypoint.d/3-configure-php-fpm.sh
> 06.05.2024 10:40:14 Configure php-fpm
> 06.05.2024 10:40:14 Launching /docker-entrypoint.d/4-configure-nginx.sh
> 06.05.2024 10:40:14 Configure nginx
> 06.05.2024 10:40:14 Launching /docker-entrypoint.d/5-configure-laravel-scheduler.sh
> 06.05.2024 10:40:14 Configure laravel scheduler
> 06.05.2024 10:40:14 Launching /docker-entrypoint.d/6-configure-laravel-horizon.sh
> 06.05.2024 10:40:14 Configure laravel horizon
> 06.05.2024 10:40:14 Launching /docker-entrypoint.d/10-configure-back.sh
> 06.05.2024 10:40:14 Configure app
> 06.05.2024 10:40:15
> 06.05.2024 10:40:15    INFO  Nothing to migrate.  
> 06.05.2024 10:40:15
> 06.05.2024 10:40:15 Configuration complete; ready for start up
> 06.05.2024 10:40:15 Running CMD: /bin/sh -c supervisord -c /etc/supervisord.conf
> 06.05.2024 10:40:15 2024-05-06 11:40:15,423 INFO Included extra file "/etc/supervisor.d/cron.ini" during parsing
> 06.05.2024 10:40:15 2024-05-06 11:40:15,423 INFO Included extra file "/etc/supervisor.d/nginx.ini" during parsing
> 06.05.2024 10:40:15 2024-05-06 11:40:15,423 INFO Included extra file "/etc/supervisor.d/node.ini" during parsing
> 06.05.2024 10:40:15 2024-05-06 11:40:15,423 INFO Included extra file "/etc/supervisor.d/php-fpm.ini" during parsing
> 06.05.2024 10:40:15 2024-05-06 11:40:15,424 INFO Set uid to user 0 succeeded
> 06.05.2024 10:40:15 2024-05-06 11:40:15,426 INFO RPC interface 'supervisor' initialized
> 06.05.2024 10:40:15 2024-05-06 11:40:15,426 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 06.05.2024 10:40:15 2024-05-06 11:40:15,426 INFO supervisord started with pid 1
> 06.05.2024 10:40:16 2024-05-06 11:40:16,428 INFO spawned: 'cron_00' with pid 43
> 06.05.2024 10:40:16 2024-05-06 11:40:16,429 INFO spawned: 'nginx_00' with pid 44
> 06.05.2024 10:40:16 2024-05-06 11:40:16,430 INFO spawned: 'node_00' with pid 45
> 06.05.2024 10:40:16 2024-05-06 11:40:16,432 INFO spawned: 'php-fpm_00' with pid 46
> 06.05.2024 10:40:16 [06-May-2024 11:40:16] NOTICE: fpm is running, pid 46
> 06.05.2024 10:40:16 [06-May-2024 11:40:16] NOTICE: ready to handle connections
> 06.05.2024 10:40:16
> 06.05.2024 10:40:16 > prod
> 06.05.2024 10:40:16 > node .output/server/index.mjs
> 06.05.2024 10:40:16
> 06.05.2024 10:40:16 Listening on http://[::]:3000
> 06.05.2024 10:40:17 2024-05-06 11:40:17,795 INFO success: cron_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 06.05.2024 10:40:17 2024-05-06 11:40:17,795 INFO success: nginx_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 06.05.2024 10:40:17 2024-05-06 11:40:17,795 INFO success: node_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 06.05.2024 10:40:17 2024-05-06 11:40:17,795 INFO success: php-fpm_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 06.05.2024 10:40:27 172.18.0.12 - - [06/May/2024:11:40:27 +0300] [0.118] [0.118] "GET / HTTP/1.1" 200 1990 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "192.168.158.30"
> 06.05.2024 10:40:37 172.18.0.12 - - [06/May/2024:11:40:37 +0300] [0.007] [0.007] "GET /_nuxt/DZR9EdxA.js HTTP/1.1" 200 15474 "https://financepico.anubis.arpa/dashboard" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "192.168.158.30"
> 06.05.2024 10:40:37 172.18.0.12 - - [06/May/2024:11:40:37 +0300] [0.007] [0.007] "GET /_nuxt/Bm1WTANA.js HTTP/1.1" 200 3308 "https://financepico.anubis.arpa/dashboard" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "192.168.158.30"
> 06.05.2024 10:40:37 172.18.0.12 - - [06/May/2024:11:40:37 +0300] [0.007] [0.007] "GET /_nuxt/useList.xR_DZ-hU.css HTTP/1.1" 200 558 "https://financepico.anubis.arpa/dashboard" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "192.168.158.30"
> 06.05.2024 10:40:37 172.18.0.12 - - [06/May/2024:11:40:37 +0300] [0.006] [0.006] "GET /_nuxt/CTQgxhJG.js HTTP/1.1" 200 5869 "https://financepico.anubis.arpa/dashboard" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "192.168.158.30"
> 06.05.2024 10:40:37 172.18.0.12 - - [06/May/2024:11:40:37 +0300] [0.007] [0.006] "GET /_nuxt/list.CRCKH7wV.css HTTP/1.1" 200 2234 "https://financepico.anubis.arpa/dashboard" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "192.168.158.30"
> 06.05.2024 10:40:56 172.18.0.12 - - [06/May/2024:11:40:56 +0300] [0.153] [0.153] "GET /api/user HTTP/1.1" 500 12487 "https://financepico.anubis.arpa/settings/app-config" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "192.168.158.30"
> 06.05.2024 10:40:56 127.0.0.1 -  06/May/2024:11:40:56 +0300 "GET /index.php" 500

I would appreciate any help and happily provide additional info if you need it.

Thanks. :)

**Comment by Teonyr** [comment]
Okay, I found the issue:
In my docker-compose.yml I set the environment variable "FIREFLY_URL" for the pico container to `http://firefly-app`.
As it turns out, pico then tries to connect to `firefly-app:80`, but since firefly uses port 8080, this doesn't succeed.

Setting the port manually to 8080 fixes the issue:
`- FIREFLY_URL=firefly-app:8080`

**Comment by Cloufish** [comment]
I have very similar issue

I run the app behind traefik, but that shouldn't be the reason.
I already had fireflyiii installed

My config:

```yml
version: "3.5"


services:
  fireflypico:
    image: cioraneanu/firefly-pico:latest
    container_name: fireflypico
    ports:
      - "80"
    networks:
      - web
      - fireflypico
    volumes:
      - fireflypico-volume:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - FIREFLY_URL=https://fireflyiii.home
      - DB_CONNECTION=pgsql
      - DB_HOST=fireflypico_db
      - DB_PORT=5432
      - DB_DATABASE=firefly-pico
      - DB_USERNAME=firefly-pico
      - DB_PASSWORD=[REDACTED - SAME AS POSTGRES_PASSWORD]
    depends_on:
      - fireflypico_db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fireflypico.rule=Host(`fireflypico.home`)"
        - "traefik.http.services.fireflypico.loadbalancer.server.port=80"
        - "traefik.docker.network=web"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.http.routers.fireflypico.tls=true"
  fireflypico_db:
    image: postgres:latest
    container_name: fireflypico_db
    environment:
      - POSTGRES_DB=firefly-pico
      - POSTGRES_USER=firefly-pico
      - POSTGRES_PASSWORD=[REDACTED - SAME AS DB_PASSWORD]
    volumes:
      - /home/swarm/fireflypico/:/var/lib/postgresql/data
    networks:
      - fireflypico

networks:
  fireflypico:
    driver: overlay
    attachable: true
    name: fireflypico
  web:
    external: true
    name: web

volumes:
  fireflypico-volume:
    driver: local
```
![image](https://github.com/cioraneanu/firefly-pico/assets/32965886/4c5be12e-ef61-4499-a696-a0455695177c)


Because of traefik I don't need to specify the port in `FIREFLY_URL=` (right?)
Please help

**Comment by cioraneanu** [comment]
In the screenshot don't put any trailing "/" in the Pico backend URL.

If that's not it, you need to make sure that from your Pico container you can actually reach the Firefly API.

Ex. `curl --location 'https://firefly.example.com/api/v1/about/user' --header 'authorization: Bearer xxxx'` (replace firefly.example.com with your Firefly URL and xxxx with your personal token).

**Comment by asherljh** [comment]
Hi there, am facing the same issue as above. 
![image](https://github.com/user-attachments/assets/7bc4e287-d6ff-4241-a2ed-620dd5042e2d)

I tried the fix suggested [here](https://github.com/cioraneanu/firefly-pico/issues/1#issuecomment-2095510994) but was unable to resolve this:
> Okay, I found the issue:
> In my docker-compose.yml I set the environment variable "FIREFLY_URL" for the pico container to `http://firefly-app`.
> As it turns out, pico then tries to connect to `firefly-app:80`, but since firefly uses port 8080, this doesn't succeed.

The Pico backend URL is configured to be Pico's IP address and port.

I have tested several different settings for the FIREFLY_URL env variable to no avail:
1. firefly_app:8080 ("firefly_app" is the name of the firefly app service in the docker compose file)
2. http://firefly_app:8080
3. http://192.168.39.21:3380 (this points to the ff3 docker container whose ports are published)

This is the pico part of my docker compose file (the br_main network is for reverse proxy with nginx proxy manager):

```
  firefly_pico:
    image: cioraneanu/firefly-pico:latest
    container_name: firefly_pico
    restart: unless-stopped
    depends_on:
      - firefly_pico_postgresql
    ports:
      - 3381:80
    environment:
      - FIREFLY_URL=firefly_app:8080
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly_pico_postgresql
      - DB_PORT=5432
      - DB_DATABASE=firefly_pico
      - DB_USERNAME=firefly_pico
      - DB_PASSWORD={...} 
      - TZ=Asia/Singapore
    networks:
      - firefly
      - br_main
```

Appreciate your help on this and this is a great project.

**Comment by cioraneanu** [comment]
For the `FIREFLY_URL ` you should go for option 3 (http://192.168.39.21:3380). Double check that opening that link opens up Firefly III. 

The Pico container cannot reach the Firefly III REST API or the authorization token is not OK. 

SSH into the Pico container and make sure this works:
`curl --location 'http://192.168.39.21:3380/api/v1/about/user' --header 'authorization: Bearer xxxx'`

**Comment by asherljh** [comment]
Thanks for the quick reply. I checked that `http://192.168.39.21:3380/` opens up Firefly III, and used it - but am still getting the same error.

Interestingly, when I use `http://ff3.mydomain.com` which I have set up using Nginx Proxy Manager for TLS and tested to work in my browser, I get these two messages in quick succession - 

> Error: Unauthorized
> Settings Saved

Navigating to the other pages in Pico gives me 

> Error: Unauthenticated 

Am quite new to all this, but my current setup has all my docker containers in a debian VM. I SSHed into the VM and ran an interactive shell of the Pico container using sh - but when I tried to run the command which you provided, it gave me:

> sh: curl: not found

How do I SSH into the container properly or install curl in the container? Thanks

**Comment by asherljh** [comment]
Did more trial and error. For reference, I had originally deployed everything using the [third compose file ](https://github.com/cioraneanu/firefly-pico/blob/main/docker-compose.pico+firefly+importer.yml)(Pico + Firefly + Importer) in the Pico [Installation](https://github.com/cioraneanu/firefly-pico/blob/main/docs/installation.md ) page.

This was my compose:

```
services:
#########################################
  firefly_pico:
    image: cioraneanu/firefly-pico:latest
    container_name: firefly_pico
    restart: unless-stopped
    depends_on:
      - firefly_pico_postgresql
    ports:
      - 3381:80
    environment:
      - FIREFLY_URL=http://firefly.dom.tld
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly_pico_postgresql
      - DB_PORT=5432
      - DB_DATABASE=firefly_pico
      - DB_USERNAME=firefly_pico
      - DB_PASSWORD={insert}
      - TZ=Asia/Singapore
    networks:
      - firefly
      - br_main
#########################################
  firefly_pico_postgresql:
    image: postgres:latest
    container_name: firefly_pico_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=firefly_pico
      - POSTGRES_USER=firefly_pico
      - POSTGRES_PASSWORD={insert}
      - TZ=Asia/Singapore
    volumes:
      - /docker_data/ff3/firefly_pico_db:/var/lib/postgresql/data
    networks:
      - firefly
#########################################
  firefly_app:
    image: fireflyiii/core:latest
    container_name: firefly_app
    restart: unless-stopped
    depends_on:
      - firefly_app_postgresql
    ports:
      - 3380:8080
    env_file:
      - stack.env
    volumes:
      - /docker_data/ff3/upload:/var/www/html/storage/upload
    networks:
      - firefly
      - br_main
#########################################
  firefly_app_postgresql:
    image: postgres:latest
    container_name: firefly_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=firefly
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD={insert}
    volumes:
      - /docker_data/ff3/db:/var/lib/postgresql/data
    networks:
      - firefly
#########################################
  importer:
    image: fireflyiii/data-importer:latest
    restart: unless-stopped
    container_name: firefly_iii_importer
    ports:
      - 3382:8080
    depends_on:
      - firefly_app
    environment:
      - SPECTRE_APP_ID={insert}
      - SPECTRE_SECRET={insert}
      - FIREFLY_III_URL=firefly_app:8080
      - VANITY_URL=http://firefly.dom.tld 
      - TZ=Asia/Singapore
      - TRUSTED_PROXIES=*
    networks:
      - firefly
      - br_main

networks:
  firefly:
    driver: bridge
  br_main:
    external: true
```

**Comment by asherljh** [comment]
Did more trial and error and noting down my findings in case helpful. For reference, I had originally deployed everything using the [third compose file](https://github.com/cioraneanu/firefly-pico/blob/main/docker-compose.pico+firefly+importer.yml) (Pico + Firefly + Importer) in the Pico [Installation](https://github.com/cioraneanu/firefly-pico/blob/main/docs/installation.md) page.

This was my compose in full (reverse proxy with a vanilla nginx proxy manager setup in the br_proxy network):

```
services:
#########################################
  firefly_pico:
    image: cioraneanu/firefly-pico:latest
    container_name: firefly_pico
    restart: unless-stopped
    depends_on:
      - firefly_pico_postgresql
    ports:
      - 3381:80
    environment:
      - FIREFLY_URL=http://firefly.dom.tld
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly_pico_postgresql
      - DB_PORT=5432
      - DB_DATABASE=firefly_pico
      - DB_USERNAME=firefly_pico
      - DB_PASSWORD=<insert>
      - TZ=Asia/Singapore
    networks:
      - firefly
      - br_proxy
#########################################
  firefly_pico_postgresql:
    image: postgres:latest
    container_name: firefly_pico_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=firefly_pico
      - POSTGRES_USER=firefly_pico
      - POSTGRES_PASSWORD=<insert>
      - TZ=Asia/Singapore
    volumes:
      - /docker_data/ff3/firefly_pico_db:/var/lib/postgresql/data
    networks:
      - firefly
#########################################
  firefly_app:
    image: fireflyiii/core:latest
    container_name: firefly_app
    restart: unless-stopped
    depends_on:
      - firefly_app_postgresql
    ports:
      - 3380:8080
    environment:
      - FIREFLY_III_LAYOUT=v1
      - APP_URL=https://firefly.dom.tld
      - APP_KEY=<add unique 32-char key>
      - TRUSTED_PROXIES=**
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly_app_postgresql
      - DB_PORT=5432
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=<insert>
    volumes:
      - /docker_data/ff3/upload:/var/www/html/storage/upload
    networks:
      - firefly
      - br_proxy
#########################################
  firefly_app_postgresql:
    image: postgres:latest
    container_name: firefly_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=firefly
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=<insert>
    volumes:
      - /docker_data/ff3/db:/var/lib/postgresql/data
    networks:
      - firefly
#########################################
  importer:
    image: fireflyiii/data-importer:latest
    restart: unless-stopped
    container_name: firefly_iii_importer
    ports:
      - 3382:8080
    depends_on:
      - firefly_app
    environment:
      - SPECTRE_APP_ID=<insert>
      - SPECTRE_SECRET=<insert>
      - FIREFLY_III_URL=firefly_app:8080
      - VANITY_URL=http://firefly.dom.tld 
      - TZ=Asia/Singapore
      - TRUSTED_PROXIES=*
    networks:
      - firefly
      - br_proxy

networks:
  firefly:
    driver: bridge
  br_proxy:
    external: true
```

I tried connecting other services to the API - the importer and Abacus. The importer could connect with an OAuth client set up. Abacus could not connect with a personal access token. But strangely, if I set the firefly URL as the local URL http://192.168.39.21:3380 (example), instead of http:firefly.dom.tld, it would work.

After a few hours of mucking around, I gave up and decided to try re-deploying just firefly iii using the compose template on the official documentation, and using the full env file. The new compose is:

```
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    networks:
      - firefly_iii
      - br_main
    restart: unless-stopped
    volumes:
      - /docker_data/ff3/upload:/var/www/html/storage/upload
    env_file: stack.env
    ports:
      - '3380:8080'
    depends_on:
      - db
  
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    networks:
      - firefly_iii
    restart: unless-stopped
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=firefly
    - MYSQL_PASSWORD=<insert>
    - MYSQL_DATABASE=firefly
    volumes:
      - /docker_data/ff3/db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: unless-stopped
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
      - br_proxy
    ports:
      - '3381:8080'
    depends_on:
      - app
    environment:
      - FIREFLY_III_URL=http://app:8080
      - VANITY_URL=http://firefly.dom.tld
      - SPECTRE_APP_ID=<insert>
      - SPECTRE_SECRET=<insert>
      - TRUSTED_PROXIES=*
      - TZ=Asia/Singapore
      - APP_URL=http://localhost

networks:
  firefly_iii:
    driver: bridge
  br_proxy:
    external: true
```

With the second compose, I was able to get both Abacus and Waterfly to connect to my Firefly III instance using a PAT. When trying to connect to Pico using a PAT, it appears to connect (as the Last sync time changes to the current time) and at first I got this error:

> Error: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied
> The exception occurred while attempting to log: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied

Then I restarted the stack (am using portainer) and now it appears to be working! 

I have no idea what the problem could have been, but it might have to do with the Firefly III compose yml in the Pico installation instructions.
