### ISSUE TITLE
Use MariaDB instead of Postgres

### ISSUE THREAD

**Issue by JcMinarro** [cioraneanu/firefly-pico#124]
As far as Firefly is using MariaDB, would be great to use the same DB Engine.
I don't have any preference between one of other DB, but as far as we are using Docker to deploy the full stack, if we use the same DB, it will reduce the the number/size of images needed to deploy it.

**Comment by cioraneanu** [comment]
You can use either MariaDB or Postgres(or even a simple SQLite file). You can also provide an external database. Just update the `DB_*` environment variables to point to it.

```
firefly-pico:
  image: cioraneanu/firefly-pico:latest
  environment:
    - DB_CONNECTION=pgsql/mysql/sqlite
    - DB_HOST=192.xxx.xxx.xxx
    - DB_PORT=54322
    - DB_DATABASE=firefly-pico
    - DB_USERNAME=firefly-pico
    - DB_PASSWORD=firefly-pico
```
