### ISSUE TITLE
The provided endpoint + token is not correct.

### ISSUE THREAD

**Issue by rvmadeit** [cioraneanu/firefly-pico#33]
Hi, I see a similar issue #1, but it was closed I tried to connect my pico instance with my firefly but when I tried to test the connection with the line:
curl --location 'https://firefly.example.com/api/v1/about/user' --header 'authorization: Bearer xxxx' (with my instance config) I have the code error : 
`{"data":{"type":"users","id":"1","attributes":{"created_at":"2024-05-11T12:32:20+00:00","updated_at":"2024-05-11T12:32:20+00:00","email":"admin@(mydomain)","blocked":false,"blocked_code":null,"role":"owner"},"links":{"self":"https:\/\/finance.(mydomain)\/api\/v1\/users\/1","0":{"rel":"self","uri":"\/users\/1"}}}}`

I use Cloudflare tunnel as reverse proxy for all my apps

**Comment by cioraneanu** [comment]
The provided curl response is good. 
In the Pico UI what have you put in the URL field?

**Comment by rvmadeit** [comment]
In the web ui i use https://finance.(my domaine name) and my personal token that i copy in the firefly instance (profil->oauth-> Personal access tokens

**Comment by rvmadeit** [comment]
![Capture d'écran 2024-05-11 203009](https://github.com/cioraneanu/firefly-pico/assets/74316943/5c5ea016-d66b-4260-8103-466efa2fc860)

**Comment by cioraneanu** [comment]
Is `finance.domain` a proxy for your Firefly or Pico instance? 

You need it to point to Pico.

**Comment by rvmadeit** [comment]
finance.domain is my firefly instance url

here's my docker compose file:

```
version: '3.3'
services:

  firefly-pico:
    image: cioraneanu/firefly-pico:latest
    container_name: firefly_pico
    restart: always
    depends_on:
      - firefly-pico-postgresql
    ports:
      - 6976:80
    environment:
      - FIREFLY_URL=https://finance.domain
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly-pico-postgresql
      - DB_PORT=54322
      - DB_DATABASE=firefly-pico
      - DB_USERNAME=firefly-pico
      - DB_PASSWORD=
      - TZ=Europe/Paris
    networks:
      firefly:

  firefly-pico-postgresql:
    image: postgres:latest
    container_name: firefly_pico_db
    restart: always
    ports:
      - 5478:54322
    environment:
      - POSTGRES_DB=firefly-pico
      - POSTGRES_USER=firefly-pico
      - POSTGRES_PASSWORD=
    volumes:
      - ./firefly-pico-db:/var/lib/postgresql/data
    networks:
      firefly:


  firefly-app:
    image: fireflyiii/core:latest
    container_name: firefly_iii
    restart: always
    depends_on:
      - firefly-app-postgresql
    ports:
      - 6041:8080
    environment:
      - FIREFLY_III_LAYOUT=v1
      - APP_URL=https://finance.domain
      - APP_KEY=2wFUmO6LhQXl4sxcg4fY4AQrzuB48OZ5
      - TRUSTED_PROXIES=**
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly-app-postgresql
      - DB_PORT=5432
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=
    volumes:
      - ./firefly-upload:/var/www/html/storage/upload
    networks:
      firefly:

  firefly-app-postgresql:
    image: postgres:latest
    container_name: firefly_iii_db
    restart: always
    ports:
      - 5498:5432
    environment:
      - POSTGRES_DB=firefly
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=
    volumes:
         - ./firefly-db:/var/lib/postgresql/data
    networks:
      firefly:

networks:
  firefly:
```
