### ISSUE TITLE
Accounts table missing (?)

### ISSUE THREAD

**Issue by chivagio** [cioraneanu/firefly-pico#35]
Hi, I can't seem to make this work. I'm getting the following error message : 

```Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'firefly-pico.accounts' doesn't exist (Connection: mysql, SQL: select * from `accounts` where `id` in (470, 683, 24, 78, 56, 257, 472, 618, 657, 663, 720, 361, 327, 340, 368, 271, 43, 567, 795, 393, 572, 796, 129, 207, 278, 561, 802, 665, 88, 741, 634, 702, 718, 610, 280, 722, 449, 710, 62, 184, 165, 715, 131, 54, 231, 302, 689, 643, 15, 381))```

My config : 
 ```
  firefly-pico:
    image: cioraneanu/firefly-pico:latest
    container_name: firefly_pico
    ports:
      - "6976:80"
    environment:
      - FIREFLY_URL=http://XXX.XXX.XXX.XXX:8081
      - DB_CONNECTION=mysql
      - DB_HOST=XXX.XXX.XXX.XXX
      - DB_PORT=3306
      - DB_DATABASE=XXXXX
      - DB_USERNAME=XXXXX
      - DB_PASSWORD=XXXXX
      - TZ=Europe/Brussels
```

I've checked the DB and I see 7 tables, but none called "accounts" : 
![image](https://github.com/cioraneanu/firefly-pico/assets/46843213/9a3fe309-963d-401c-9c1a-1e8ca6a130a6)

Am I doing something wrong ?
